kind: pipeline
type: docker
name: default

clone:
  depth: 50

steps:
  - name: test
    image: golang:1.21
    commands:
      - go mod tidy
      - go mod download
      - go test -v ./...

  - name: lint
    image: golang:1.21
    commands:	
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
      - golangci-lint run ./...
